### PR TITLE
Update module from upstream

### PR DESCRIPTION
**Pull request by iuriaranda**
These are the changes that puppet does after upgrading the module version:

```
==> 1404: Notice: /Stage[main]/Elasticsearch::Package/Exec[create_package_dir_elasticsearch]/returns: executed successfully
==> 1404: Notice: /Stage[main]/Elasticsearch::Config/File[/usr/share/elasticsearch/shield]/ensure: created
==> 1404: Notice: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Plugin[cloud-aws]/Elasticsearch_plugin[cloud-aws]/ensure: created
==> 1404: Notice: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/File[/etc/elasticsearch/sweepbright-es/shield]/ensure: created
==> 1404: Notice: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Datacat[/etc/elasticsearch/sweepbright-es/elasticsearch.yml]/File[/etc/elasticsearch/sweepbright-es/elasticsearch.yml]/content:
==> 1404: --- /etc/elasticsearch/sweepbright-es/elasticsearch.yml       2016-10-18 03:03:21.646851875 -0700
==> 1404: +++ /tmp/puppet-file20161018-5327-c9nevf      2016-10-18 03:22:04.899806563 -0700
==> 1404: @@ -1,23 +1,14 @@
==> 1404:  ### MANAGED BY PUPPET ###
==> 1404: ----
==> 1404: -discovery:
==> 1404: -  ec2:
==> 1404: -    tag: production
==> 1404: -  type: ec2
==> 1404: -  zen:
==> 1404: -    ping:
==> 1404: -      multicast:
==> 1404: -        enabled: false
==> 1404: -      timeout: 30s
==> 1404: -index:
==> 1404: -  number_of_replicas: 1
==> 1404: -network:
==> 1404: -  bind_host: 0.0.0.0
==> 1404: -node:
==> 1404: -  name: sweepbright-elasticsearch01
==> 1404: -path:
==> 1404: -  data: /usr/share/elasticsearch/data/sweepbright-es
==> 1404: -  repo: /opt/skyscrapers/backup/elasticsearch
==> 1404: -script:
==> 1404: -  indexed: on
==> 1404: -  inline: on
==> 1404: +---
==> 1404: +discovery.ec2.tag: production
==> 1404: +discovery.type: ec2
==> 1404: +discovery.zen.ping.multicast.enabled: false
==> 1404: +discovery.zen.ping.timeout: "30s"
==> 1404: +index.number_of_replicas: 1
==> 1404: +network.bind_host: "0.0.0.0"
==> 1404: +node.name: sweepbright-elasticsearch01
==> 1404: +path.data: /usr/share/elasticsearch/data/sweepbright-es
==> 1404: +path.logs: /var/log/elasticsearch/sweepbright-es
==> 1404: +path.repo: /opt/skyscrapers/backup/elasticsearch
==> 1404: +script.indexed: "on"
==> 1404: +script.inline: "on"
==> 1404:
==> 1404: Info: Computing checksum on file /etc/elasticsearch/sweepbright-es/elasticsearch.yml
==> 1404: Info: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Datacat[/etc/elasticsearch/sweepbright-es/elasticsearch.yml]/File[/etc/elasticsearch/sweepbright-es/elasticsearch.yml]: Filebucketed /etc/elasticsearch/sweepbright-es/elasticsearch.yml to puppet with sum 97890dec843cdf0ded4ed32cc7d2aab4
==> 1404: Notice: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Datacat[/etc/elasticsearch/sweepbright-es/elasticsearch.yml]/File[/etc/elasticsearch/sweepbright-es/elasticsearch.yml]/content: content changed '{md5}97890dec843cdf0ded4ed32cc7d2aab4' to '{md5}b468a01fe61b87b07daa2385626ee0a2'
==> 1404: Notice: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Elasticsearch::Service[sweepbright-es]/Elasticsearch::Service::Init[sweepbright-es]/File[/etc/init.d/elasticsearch-sweepbright-es]/content:
==> 1404: --- /etc/init.d/elasticsearch-sweepbright-es  2016-10-18 03:03:21.890729864 -0700
==> 1404: +++ /tmp/puppet-file20161018-5327-t9t7d1      2016-10-18 03:22:05.083806554 -0700
==> 1404: @@ -56,7 +56,7 @@
==> 1404:  export JAVA_HOME
==> 1404:
==> 1404:  # Directory where the Elasticsearch binary distribution resides
==> 1404: -ES_HOME=/usr/share/$NAME
==> 1404: +#ES_HOME=/usr/share/$NAME
==> 1404:
==> 1404:  # Heap Size (defaults to 256m min, 1g max)
==> 1404:  #ES_HEAP_SIZE=2g
==> 1404: @@ -77,19 +77,19 @@
==> 1404:  #MAX_LOCKED_MEMORY=
==> 1404:
==> 1404:  # Elasticsearch log directory
==> 1404: -LOG_DIR=/var/log/$NAME
==> 1404: +#LOG_DIR=/var/log/$NAME
==> 1404:
==> 1404:  # Elasticsearch data directory
==> 1404: -DATA_DIR=/var/lib/$NAME
==> 1404: +#DATA_DIR=/var/lib/$NAME
==> 1404:
==> 1404:  # Elasticsearch work directory
==> 1404:  WORK_DIR=/tmp/$NAME
==> 1404:
==> 1404:  # Elasticsearch configuration directory
==> 1404: -CONF_DIR=/etc/$NAME
==> 1404: +#CONF_DIR=/etc/$NAME
==> 1404:
==> 1404:  # Elasticsearch configuration file (elasticsearch.yml)
==> 1404: -CONF_FILE=$CONF_DIR/elasticsearch.yml
==> 1404: +#CONF_FILE=$CONF_DIR/elasticsearch.yml
==> 1404:
==> 1404:  # Maximum number of VMA (Virtual Memory Areas) a process can own
==> 1404:  MAX_MAP_COUNT=262144
==> 1404: @@ -111,6 +111,8 @@
==> 1404:  export ES_DIRECT_SIZE
==> 1404:  export ES_JAVA_OPTS
==> 1404:  export ES_CLASSPATH
==> 1404: +export ES_INCLUDE
==> 1404: +export ES_GC_LOG_FILE
==> 1404:
==> 1404:  # Check DAEMON exists
==> 1404:  test -x $DAEMON || exit 0
==> 1404: @@ -147,7 +149,9 @@
==> 1404:       fi
==> 1404:
==> 1404:       # Prepare environment
==> 1404: -     mkdir -p "$LOG_DIR" "$DATA_DIR" "$WORK_DIR" && chown "$ES_USER":"$ES_GROUP" "$LOG_DIR" "$DATA_DIR" "$WORK_DIR"
==> 1404: +     for DIR in "$DATA_DIR" "$LOG_DIR" "$WORK_DIR"; do
==> 1404: +             [ ! -z "$DIR" ] && mkdir -p "$DIR" && chown "$ES_USER":"$ES_GROUP" "$DIR"
==> 1404: +     done
==> 1404:       touch "$PID_FILE" && chown "$ES_USER":"$ES_GROUP" "$PID_FILE"
==> 1404:
==> 1404:       if [ -n "$MAX_OPEN_FILES" ]; then
==> 1404:
==> 1404: Info: Computing checksum on file /etc/init.d/elasticsearch-sweepbright-es
==> 1404: Info: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Elasticsearch::Service[sweepbright-es]/Elasticsearch::Service::Init[sweepbright-es]/File[/etc/init.d/elasticsearch-sweepbright-es]: Filebucketed /etc/init.d/elasticsearch-sweepbright-es to puppet with sum 69588edc044015d143719ecd979f8379
==> 1404: Notice: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Elasticsearch::Service[sweepbright-es]/Elasticsearch::Service::Init[sweepbright-es]/File[/etc/init.d/elasticsearch-sweepbright-es]/content: content changed '{md5}69588edc044015d143719ecd979f8379' to '{md5}16598842d2f2fe1d8cda4c1d361a1af5'
==> 1404: Notice: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Elasticsearch::Service[sweepbright-es]/Elasticsearch::Service::Init[sweepbright-es]/Service[elasticsearch-instance-sweepbright-es]/ensure: ensure changed 'stopped' to 'running'
==> 1404: Info: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Elasticsearch::Service[sweepbright-es]/Elasticsearch::Service::Init[sweepbright-es]/Service[elasticsearch-instance-sweepbright-es]: Unscheduling refresh on Service[elasticsearch-instance-sweepbright-es]
==> 1404: Notice: Finished catalog run in 41.41 seconds
```

### CODE REVIEW

**Comment by MattiasGees** [comment]
@iuriaranda is there a setting in elasticsearch to not restart the service when there are changes in the config file? I don't want this to restart our clusters :)

**Comment by iuriaranda** [comment]
@MattiasGees yes there is: `restart_config_change`, but it's only available after merging this. So either I set it as default in this module, or I add it to all our clusters at the same time I bump this module.

I prefer to go for the first option

**Comment by iuriaranda** [comment]
I'm getting the same error as with our current module version:

```
==> 1604: Error: Could not start Service[elasticsearch-instance-sweepbright-es]: Execution of '/bin/systemctl start elasticsearch-sweepbright-es.service' returned 1: Job for elasticsearch-sweepbright-es.service failed because a configured resource limit was exceeded. See "systemctl status elasticsearch-sweepbright-es.service" and "journalctl -xe" for details.
==> 1604: Error: /Stage[main]/Sweepbright::Profiles::Elasticsearch/Elasticsearch::Instance[sweepbright-es]/Elasticsearch::Service[sweepbright-es]/Elasticsearch::Service::Systemd[sweepbright-es]/Service[elasticsearch-instance-sweepbright-es]/ensure: change from stopped to running failed: Could not start Service[elasticsearch-instance-sweepbright-es]: Execution of '/bin/systemctl start elasticsearch-sweepbright-es.service' returned 1: Job for elasticsearch-sweepbright-es.service failed because a configured resource limit was exceeded. See "systemctl status elasticsearch-sweepbright-es.service" and "journalctl -xe" for details.
```

So 16.04 might not be supported on the upstream module neither.

**Comment by iuriaranda** [comment]
Merged from `0.16.0` release, as it's the latest stable release. Closing this.

Ref: https://github.com/skyscrapers/puppet/issues/3472

**Pull request closed without merging**
